"""Canonical cross-module records."""

from ses.contracts.artifact import (
    ArtifactRef,
    ArtifactRoot,
    JsonPointer,
    RelativeArtifactPath,
    Sha256Digest,
)
from ses.contracts.base import ContractModel, VersionedRecord
from ses.contracts.case import CaseDefinition, CaseSplit
from ses.contracts.engine import (
    CompletedPayload,
    EngineEvent,
    EngineEventKind,
    EngineEventPayload,
    EngineExitStatus,
    EngineRequest,
    ErrorPayload,
    TextDeltaPayload,
    ToolCallPayload,
    ToolResultPayload,
    UnknownPayload,
    Usage,
    UsagePayload,
)
from ses.contracts.evaluation import (
    AssertionResult,
    CaseGrade,
    EvidenceRef,
    GradeStatus,
    JudgeKind,
    Trace,
)
from ses.contracts.primitives import (
    AssertionId,
    CaseId,
    CurrencyCode,
    DiffId,
    EventId,
    GradeId,
    IterationId,
    MessageId,
    NonEmptyStr,
    OpaqueId,
    RecordType,
    RequestId,
    RunId,
    SchemaVersion,
    SessionId,
    SnapshotId,
    StrictNonNegativeInt,
    ToolCallId,
    TraceId,
    UtcDateTime,
)
from ses.contracts.serialization import artifact_json_bytes, content_sha256
from ses.contracts.shop import (
    Money,
    ShopSnapshot,
    StateChange,
    StateDiff,
    ToolResult,
    ToolResultStatus,
)

__all__ = [
    "ArtifactRef",
    "ArtifactRoot",
    "AssertionId",
    "AssertionResult",
    "CaseDefinition",
    "CaseGrade",
    "CaseId",
    "CaseSplit",
    "CompletedPayload",
    "ContractModel",
    "CurrencyCode",
    "DiffId",
    "EngineEvent",
    "EngineEventKind",
    "EngineEventPayload",
    "EngineExitStatus",
    "EngineRequest",
    "ErrorPayload",
    "EventId",
    "EvidenceRef",
    "GradeId",
    "GradeStatus",
    "IterationId",
    "JsonPointer",
    "JudgeKind",
    "MessageId",
    "Money",
    "NonEmptyStr",
    "OpaqueId",
    "RecordType",
    "RelativeArtifactPath",
    "RequestId",
    "RunId",
    "SchemaVersion",
    "SessionId",
    "Sha256Digest",
    "ShopSnapshot",
    "SnapshotId",
    "StateChange",
    "StateDiff",
    "StrictNonNegativeInt",
    "TextDeltaPayload",
    "ToolCallId",
    "ToolCallPayload",
    "ToolResult",
    "ToolResultPayload",
    "ToolResultStatus",
    "Trace",
    "TraceId",
    "UnknownPayload",
    "Usage",
    "UsagePayload",
    "UtcDateTime",
    "VersionedRecord",
    "artifact_json_bytes",
    "content_sha256",
]
